/********************************************************************************
** Form generated from reading UI file 'monitor2023.ui'
**
** Created by: Qt User Interface Compiler version 5.12.8
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MONITOR2023_H
#define UI_MONITOR2023_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QFrame>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QProgressBar>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Monitor2023
{
public:
    QWidget *centralwidget;
    QFrame *frame_LiDAR;
    QLabel *img_depth;
    QLabel *label_depth;
    QLabel *label_reflectivity;
    QLabel *img_reflectivity;
    QFrame *frame_Mercury_status;
    QLabel *label_mercury_status;
    QLabel *label_temp;
    QLabel *label_temp_CPU;
    QLabel *label_battery;
    QProgressBar *progressBar_battery;
    QProgressBar *progressBar_temp;
    QProgressBar *progressBar_temp_CPU;
    QLabel *Mercury;
    QLabel *label_sonar;
    QLabel *Sonar_front_left;
    QLabel *Sonar_front_center;
    QLabel *Sonar_front_right;
    QLabel *Sonar_left;
    QLabel *Sonar_right;
    QLabel *Sonar_rear_left;
    QLabel *Sonar_rear_right;
    QLabel *label_bolt;
    QLabel *tire_front_left;
    QLabel *tire_front_right;
    QLabel *tire_rear_left;
    QLabel *tire_rear_right;
    QLabel *label_mileage;
    QLabel *box_mileage;
    QLabel *label_mileage_m;
    QLabel *rpm_front_right;
    QLabel *rpm_rear_right;
    QLabel *rpm_rear_left;
    QLabel *rpm_front_left;
    QFrame *frame_Node_status;
    QLabel *label_node_status;
    QLabel *label_3DLiDAR_H;
    QLabel *light_3DLiDAR_H;
    QLabel *label_3DLiDAR_M;
    QLabel *light_3DLiDAR_M;
    QLabel *label_2DLiDAR_L;
    QLabel *light_2DLiDAR_L;
    QLabel *label_camera_status;
    QLabel *light_camera_status;
    QLabel *label_Mercury;
    QLabel *label_Sonar;
    QLabel *label_waypoint;
    QLabel *light_Mercury;
    QLabel *light_sonar;
    QLabel *label_Mercury_run;
    QLabel *light_waypoint;
    QLabel *light_Mercury_run;
    QLabel *label_path_following;
    QLabel *label_path_plannning;
    QLabel *label_road_sign;
    QLabel *label_obstacle;
    QLabel *label_logger;
    QLabel *light_path_planning;
    QLabel *light_path_following;
    QLabel *light_points_proc;
    QLabel *light_road_sign;
    QLabel *light_logger;
    QLabel *label_locator;
    QLabel *label_points_proc;
    QLabel *light_obstacle;
    QLabel *light_locator;
    QLabel *light_joystick;
    QLabel *label_joystick;
    QLabel *light_container;
    QLabel *label_container;
    QLabel *label_traffic_light;
    QLabel *light_traffic_light;
    QFrame *frame_map;
    QLabel *img_obstacle_detector;
    QLabel *label_obstacle_detector;
    QLabel *img_matcing_img;
    QLabel *label_matching_img;
    QLabel *img_map;
    QLabel *label_map;
    QFrame *frame_waypoint;
    QLabel *label_waypoint_2;
    QLabel *label_waypoint_file;
    QLabel *label_waypoint_index;
    QLabel *box_waypoint_file;
    QLabel *box_waypoint_index;
    QLabel *box_waypoint_map;
    QLabel *label_waypoint_map;
    QFrame *frame_camera;
    QLabel *label_camera;
    QLabel *img_camera;
    QFrame *frame_robot_control;
    QLabel *label_robot_control;
    QLabel *label_velocity;
    QLabel *label_potential;
    QLabel *label_x1;
    QLabel *label_velocity_x;
    QLabel *label_velocity_yaw;
    QLabel *label_potential_x;
    QLabel *label_potential_yaw;
    QLabel *label_y1;
    QFrame *frame_imu;
    QLabel *label_imu;
    QLabel *label_x2;
    QLabel *label_y2;
    QLabel *label_gyro_x;
    QLabel *label_gyro_y;
    QLabel *label_accele_x;
    QLabel *label_accele_y;
    QLabel *label_angle_x;
    QLabel *label_angle_y;
    QLabel *label_angle_z;
    QLabel *label_accele_z;
    QLabel *label_z2;
    QLabel *label_gyro_z;
    QLabel *label_accele;
    QLabel *label_angle;
    QLabel *label_gyro;
    QFrame *frame;
    QLabel *box_filename;
    QLabel *label_auto;
    QLabel *box_auto;
    QLabel *box_manual;
    QLabel *label_manual;
    QLabel *label_filename;
    QLabel *label_node_status_2;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *Monitor2023)
    {
        if (Monitor2023->objectName().isEmpty())
            Monitor2023->setObjectName(QString::fromUtf8("Monitor2023"));
        Monitor2023->setEnabled(true);
        Monitor2023->resize(1750, 925);
        Monitor2023->setMinimumSize(QSize(1750, 925));
        Monitor2023->setMaximumSize(QSize(1750, 925));
        centralwidget = new QWidget(Monitor2023);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        centralwidget->setMinimumSize(QSize(1750, 925));
        centralwidget->setMaximumSize(QSize(1750, 925));
        centralwidget->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        frame_LiDAR = new QFrame(centralwidget);
        frame_LiDAR->setObjectName(QString::fromUtf8("frame_LiDAR"));
        frame_LiDAR->setGeometry(QRect(10, 510, 381, 381));
        frame_LiDAR->setFrameShape(QFrame::StyledPanel);
        frame_LiDAR->setFrameShadow(QFrame::Raised);
        img_depth = new QLabel(frame_LiDAR);
        img_depth->setObjectName(QString::fromUtf8("img_depth"));
        img_depth->setGeometry(QRect(10, 50, 351, 111));
        img_depth->setStyleSheet(QString::fromUtf8("background-color:rgb(239, 41, 41);"));
        label_depth = new QLabel(frame_LiDAR);
        label_depth->setObjectName(QString::fromUtf8("label_depth"));
        label_depth->setGeometry(QRect(10, 10, 351, 31));
        QFont font;
        font.setPointSize(19);
        label_depth->setFont(font);
        label_reflectivity = new QLabel(frame_LiDAR);
        label_reflectivity->setObjectName(QString::fromUtf8("label_reflectivity"));
        label_reflectivity->setGeometry(QRect(10, 190, 351, 31));
        label_reflectivity->setFont(font);
        img_reflectivity = new QLabel(frame_LiDAR);
        img_reflectivity->setObjectName(QString::fromUtf8("img_reflectivity"));
        img_reflectivity->setGeometry(QRect(10, 230, 351, 111));
        img_reflectivity->setStyleSheet(QString::fromUtf8("background-color: rgb(52, 101, 164);"));
        frame_Mercury_status = new QFrame(centralwidget);
        frame_Mercury_status->setObjectName(QString::fromUtf8("frame_Mercury_status"));
        frame_Mercury_status->setGeometry(QRect(1290, 10, 451, 411));
        frame_Mercury_status->setFrameShape(QFrame::StyledPanel);
        frame_Mercury_status->setFrameShadow(QFrame::Raised);
        label_mercury_status = new QLabel(frame_Mercury_status);
        label_mercury_status->setObjectName(QString::fromUtf8("label_mercury_status"));
        label_mercury_status->setGeometry(QRect(10, 10, 431, 31));
        QFont font1;
        font1.setFamily(QString::fromUtf8("Ubuntu"));
        font1.setPointSize(19);
        font1.setBold(false);
        font1.setWeight(50);
        label_mercury_status->setFont(font1);
        label_mercury_status->setStyleSheet(QString::fromUtf8(""));
        label_temp = new QLabel(frame_Mercury_status);
        label_temp->setObjectName(QString::fromUtf8("label_temp"));
        label_temp->setGeometry(QRect(170, 45, 111, 31));
        QFont font2;
        font2.setPointSize(15);
        label_temp->setFont(font2);
        label_temp_CPU = new QLabel(frame_Mercury_status);
        label_temp_CPU->setObjectName(QString::fromUtf8("label_temp_CPU"));
        label_temp_CPU->setGeometry(QRect(320, 40, 111, 31));
        label_temp_CPU->setFont(font2);
        label_battery = new QLabel(frame_Mercury_status);
        label_battery->setObjectName(QString::fromUtf8("label_battery"));
        label_battery->setGeometry(QRect(20, 45, 111, 31));
        label_battery->setFont(font2);
        progressBar_battery = new QProgressBar(frame_Mercury_status);
        progressBar_battery->setObjectName(QString::fromUtf8("progressBar_battery"));
        progressBar_battery->setGeometry(QRect(20, 115, 118, 51));
        QFont font3;
        font3.setFamily(QString::fromUtf8("Ubuntu Mono"));
        font3.setPointSize(20);
        font3.setBold(true);
        font3.setItalic(false);
        font3.setWeight(75);
        progressBar_battery->setFont(font3);
        progressBar_battery->setStyleSheet(QString::fromUtf8("selection-background-color: lime;\n"
"background-color: rgb(243, 243, 243);"));
        progressBar_battery->setValue(24);
        progressBar_temp = new QProgressBar(frame_Mercury_status);
        progressBar_temp->setObjectName(QString::fromUtf8("progressBar_temp"));
        progressBar_temp->setGeometry(QRect(170, 115, 118, 51));
        progressBar_temp->setFont(font3);
        progressBar_temp->setStyleSheet(QString::fromUtf8("selection-background-color: orange;\n"
"background-color: rgb(243, 243, 243);"));
        progressBar_temp->setMaximum(120);
        progressBar_temp->setValue(24);
        progressBar_temp_CPU = new QProgressBar(frame_Mercury_status);
        progressBar_temp_CPU->setObjectName(QString::fromUtf8("progressBar_temp_CPU"));
        progressBar_temp_CPU->setGeometry(QRect(320, 115, 118, 51));
        progressBar_temp_CPU->setFont(font3);
        progressBar_temp_CPU->setStyleSheet(QString::fromUtf8("selection-background-color: lime;\n"
"background-color: rgb(243, 243, 243);"));
        progressBar_temp_CPU->setMaximum(120);
        progressBar_temp_CPU->setValue(24);
        Mercury = new QLabel(frame_Mercury_status);
        Mercury->setObjectName(QString::fromUtf8("Mercury"));
        Mercury->setGeometry(QRect(170, 276, 100, 100));
        Mercury->setStyleSheet(QString::fromUtf8("background-color: rgb(52, 101, 164);\n"
"color: rgb(255, 255, 255);"));
        Mercury->setAlignment(Qt::AlignCenter);
        label_sonar = new QLabel(frame_Mercury_status);
        label_sonar->setObjectName(QString::fromUtf8("label_sonar"));
        label_sonar->setGeometry(QRect(20, 231, 411, 17));
        label_sonar->setFont(font2);
        Sonar_front_left = new QLabel(frame_Mercury_status);
        Sonar_front_left->setObjectName(QString::fromUtf8("Sonar_front_left"));
        Sonar_front_left->setGeometry(QRect(90, 250, 80, 21));
        QFont font4;
        font4.setPointSize(13);
        Sonar_front_left->setFont(font4);
        Sonar_front_left->setStyleSheet(QString::fromUtf8("background-color: rgb(105, 226, 240);\n"
"border:2px solid black;"));
        Sonar_front_left->setAlignment(Qt::AlignCenter);
        Sonar_front_center = new QLabel(frame_Mercury_status);
        Sonar_front_center->setObjectName(QString::fromUtf8("Sonar_front_center"));
        Sonar_front_center->setGeometry(QRect(180, 250, 80, 21));
        Sonar_front_center->setFont(font4);
        Sonar_front_center->setStyleSheet(QString::fromUtf8("background-color: rgb(105, 226, 240);\n"
"border:2px solid black;"));
        Sonar_front_center->setAlignment(Qt::AlignCenter);
        Sonar_front_right = new QLabel(frame_Mercury_status);
        Sonar_front_right->setObjectName(QString::fromUtf8("Sonar_front_right"));
        Sonar_front_right->setGeometry(QRect(270, 250, 80, 21));
        Sonar_front_right->setFont(font4);
        Sonar_front_right->setStyleSheet(QString::fromUtf8("background-color: rgb(105, 226, 240);\n"
"border:2px solid black;"));
        Sonar_front_right->setAlignment(Qt::AlignCenter);
        Sonar_left = new QLabel(frame_Mercury_status);
        Sonar_left->setObjectName(QString::fromUtf8("Sonar_left"));
        Sonar_left->setGeometry(QRect(60, 316, 80, 21));
        Sonar_left->setFont(font4);
        Sonar_left->setStyleSheet(QString::fromUtf8("background-color: rgb(105, 226, 240);\n"
"border:2px solid black;"));
        Sonar_left->setAlignment(Qt::AlignCenter);
        Sonar_right = new QLabel(frame_Mercury_status);
        Sonar_right->setObjectName(QString::fromUtf8("Sonar_right"));
        Sonar_right->setGeometry(QRect(300, 315, 80, 21));
        Sonar_right->setFont(font4);
        Sonar_right->setStyleSheet(QString::fromUtf8("background-color: rgb(105, 226, 240);\n"
"border:2px solid black;"));
        Sonar_right->setAlignment(Qt::AlignCenter);
        Sonar_rear_left = new QLabel(frame_Mercury_status);
        Sonar_rear_left->setObjectName(QString::fromUtf8("Sonar_rear_left"));
        Sonar_rear_left->setGeometry(QRect(130, 381, 80, 21));
        Sonar_rear_left->setFont(font4);
        Sonar_rear_left->setStyleSheet(QString::fromUtf8("background-color: rgb(105, 226, 240);\n"
"border:2px solid black;"));
        Sonar_rear_left->setAlignment(Qt::AlignCenter);
        Sonar_rear_right = new QLabel(frame_Mercury_status);
        Sonar_rear_right->setObjectName(QString::fromUtf8("Sonar_rear_right"));
        Sonar_rear_right->setGeometry(QRect(230, 381, 80, 21));
        Sonar_rear_right->setFont(font4);
        Sonar_rear_right->setStyleSheet(QString::fromUtf8("background-color: rgb(105, 226, 240);\n"
"border:2px solid black;"));
        Sonar_rear_right->setAlignment(Qt::AlignCenter);
        label_bolt = new QLabel(frame_Mercury_status);
        label_bolt->setObjectName(QString::fromUtf8("label_bolt"));
        label_bolt->setGeometry(QRect(20, 80, 111, 31));
        QFont font5;
        font5.setFamily(QString::fromUtf8("Ubuntu Condensed"));
        font5.setPointSize(20);
        font5.setBold(true);
        font5.setWeight(75);
        label_bolt->setFont(font5);
        tire_front_left = new QLabel(frame_Mercury_status);
        tire_front_left->setObjectName(QString::fromUtf8("tire_front_left"));
        tire_front_left->setGeometry(QRect(151, 277, 16, 31));
        tire_front_left->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        tire_front_right = new QLabel(frame_Mercury_status);
        tire_front_right->setObjectName(QString::fromUtf8("tire_front_right"));
        tire_front_right->setGeometry(QRect(272, 277, 16, 31));
        tire_front_right->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        tire_rear_left = new QLabel(frame_Mercury_status);
        tire_rear_left->setObjectName(QString::fromUtf8("tire_rear_left"));
        tire_rear_left->setGeometry(QRect(152, 344, 16, 31));
        tire_rear_left->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        tire_rear_right = new QLabel(frame_Mercury_status);
        tire_rear_right->setObjectName(QString::fromUtf8("tire_rear_right"));
        tire_rear_right->setGeometry(QRect(272, 344, 16, 31));
        tire_rear_right->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        label_mileage = new QLabel(frame_Mercury_status);
        label_mileage->setObjectName(QString::fromUtf8("label_mileage"));
        label_mileage->setGeometry(QRect(20, 180, 91, 31));
        label_mileage->setFont(font2);
        box_mileage = new QLabel(frame_Mercury_status);
        box_mileage->setObjectName(QString::fromUtf8("box_mileage"));
        box_mileage->setGeometry(QRect(130, 180, 261, 31));
        QFont font6;
        font6.setPointSize(20);
        box_mileage->setFont(font6);
        box_mileage->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        box_mileage->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_mileage_m = new QLabel(frame_Mercury_status);
        label_mileage_m->setObjectName(QString::fromUtf8("label_mileage_m"));
        label_mileage_m->setGeometry(QRect(400, 180, 31, 31));
        label_mileage_m->setFont(font6);
        rpm_front_right = new QLabel(frame_Mercury_status);
        rpm_front_right->setObjectName(QString::fromUtf8("rpm_front_right"));
        rpm_front_right->setGeometry(QRect(300, 280, 80, 21));
        rpm_front_right->setFont(font4);
        rpm_front_right->setStyleSheet(QString::fromUtf8("background-color: rgb(186, 189, 182);\n"
"border:2px solid black;"));
        rpm_front_right->setAlignment(Qt::AlignCenter);
        rpm_rear_right = new QLabel(frame_Mercury_status);
        rpm_rear_right->setObjectName(QString::fromUtf8("rpm_rear_right"));
        rpm_rear_right->setGeometry(QRect(300, 350, 80, 21));
        rpm_rear_right->setFont(font4);
        rpm_rear_right->setStyleSheet(QString::fromUtf8("background-color: rgb(186, 189, 182);\n"
"border:2px solid black;"));
        rpm_rear_right->setAlignment(Qt::AlignCenter);
        rpm_rear_left = new QLabel(frame_Mercury_status);
        rpm_rear_left->setObjectName(QString::fromUtf8("rpm_rear_left"));
        rpm_rear_left->setGeometry(QRect(60, 350, 80, 21));
        rpm_rear_left->setFont(font4);
        rpm_rear_left->setStyleSheet(QString::fromUtf8("background-color: rgb(186, 189, 182);\n"
"border:2px solid black;"));
        rpm_rear_left->setAlignment(Qt::AlignCenter);
        rpm_front_left = new QLabel(frame_Mercury_status);
        rpm_front_left->setObjectName(QString::fromUtf8("rpm_front_left"));
        rpm_front_left->setGeometry(QRect(60, 280, 80, 21));
        rpm_front_left->setFont(font4);
        rpm_front_left->setStyleSheet(QString::fromUtf8("background-color: rgb(186, 189, 182);\n"
"border:2px solid black;"));
        rpm_front_left->setAlignment(Qt::AlignCenter);
        frame_Node_status = new QFrame(centralwidget);
        frame_Node_status->setObjectName(QString::fromUtf8("frame_Node_status"));
        frame_Node_status->setGeometry(QRect(1290, 430, 451, 381));
        frame_Node_status->setFrameShape(QFrame::StyledPanel);
        frame_Node_status->setFrameShadow(QFrame::Raised);
        label_node_status = new QLabel(frame_Node_status);
        label_node_status->setObjectName(QString::fromUtf8("label_node_status"));
        label_node_status->setGeometry(QRect(10, 10, 431, 31));
        label_node_status->setFont(font);
        label_3DLiDAR_H = new QLabel(frame_Node_status);
        label_3DLiDAR_H->setObjectName(QString::fromUtf8("label_3DLiDAR_H"));
        label_3DLiDAR_H->setGeometry(QRect(20, 50, 151, 35));
        QFont font7;
        font7.setPointSize(16);
        label_3DLiDAR_H->setFont(font7);
        light_3DLiDAR_H = new QLabel(frame_Node_status);
        light_3DLiDAR_H->setObjectName(QString::fromUtf8("light_3DLiDAR_H"));
        light_3DLiDAR_H->setGeometry(QRect(180, 57, 41, 20));
        light_3DLiDAR_H->setFont(font7);
        light_3DLiDAR_H->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);"));
        light_3DLiDAR_H->setAlignment(Qt::AlignCenter);
        label_3DLiDAR_M = new QLabel(frame_Node_status);
        label_3DLiDAR_M->setObjectName(QString::fromUtf8("label_3DLiDAR_M"));
        label_3DLiDAR_M->setGeometry(QRect(20, 80, 151, 35));
        label_3DLiDAR_M->setFont(font7);
        light_3DLiDAR_M = new QLabel(frame_Node_status);
        light_3DLiDAR_M->setObjectName(QString::fromUtf8("light_3DLiDAR_M"));
        light_3DLiDAR_M->setGeometry(QRect(180, 87, 41, 20));
        light_3DLiDAR_M->setFont(font7);
        light_3DLiDAR_M->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);"));
        light_3DLiDAR_M->setAlignment(Qt::AlignCenter);
        label_2DLiDAR_L = new QLabel(frame_Node_status);
        label_2DLiDAR_L->setObjectName(QString::fromUtf8("label_2DLiDAR_L"));
        label_2DLiDAR_L->setGeometry(QRect(20, 110, 151, 35));
        label_2DLiDAR_L->setFont(font7);
        light_2DLiDAR_L = new QLabel(frame_Node_status);
        light_2DLiDAR_L->setObjectName(QString::fromUtf8("light_2DLiDAR_L"));
        light_2DLiDAR_L->setGeometry(QRect(180, 117, 41, 20));
        light_2DLiDAR_L->setFont(font7);
        light_2DLiDAR_L->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);"));
        light_2DLiDAR_L->setAlignment(Qt::AlignCenter);
        label_camera_status = new QLabel(frame_Node_status);
        label_camera_status->setObjectName(QString::fromUtf8("label_camera_status"));
        label_camera_status->setGeometry(QRect(20, 140, 151, 35));
        label_camera_status->setFont(font7);
        light_camera_status = new QLabel(frame_Node_status);
        light_camera_status->setObjectName(QString::fromUtf8("light_camera_status"));
        light_camera_status->setGeometry(QRect(180, 147, 41, 20));
        light_camera_status->setFont(font7);
        light_camera_status->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);"));
        light_camera_status->setAlignment(Qt::AlignCenter);
        label_Mercury = new QLabel(frame_Node_status);
        label_Mercury->setObjectName(QString::fromUtf8("label_Mercury"));
        label_Mercury->setGeometry(QRect(20, 200, 141, 35));
        label_Mercury->setFont(font7);
        label_Sonar = new QLabel(frame_Node_status);
        label_Sonar->setObjectName(QString::fromUtf8("label_Sonar"));
        label_Sonar->setGeometry(QRect(20, 170, 151, 35));
        label_Sonar->setFont(font7);
        label_waypoint = new QLabel(frame_Node_status);
        label_waypoint->setObjectName(QString::fromUtf8("label_waypoint"));
        label_waypoint->setGeometry(QRect(20, 260, 151, 35));
        label_waypoint->setFont(font7);
        light_Mercury = new QLabel(frame_Node_status);
        light_Mercury->setObjectName(QString::fromUtf8("light_Mercury"));
        light_Mercury->setGeometry(QRect(180, 207, 41, 20));
        light_Mercury->setFont(font7);
        light_Mercury->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);"));
        light_Mercury->setAlignment(Qt::AlignCenter);
        light_sonar = new QLabel(frame_Node_status);
        light_sonar->setObjectName(QString::fromUtf8("light_sonar"));
        light_sonar->setGeometry(QRect(180, 177, 41, 20));
        light_sonar->setFont(font7);
        light_sonar->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);"));
        light_sonar->setAlignment(Qt::AlignCenter);
        label_Mercury_run = new QLabel(frame_Node_status);
        label_Mercury_run->setObjectName(QString::fromUtf8("label_Mercury_run"));
        label_Mercury_run->setGeometry(QRect(20, 230, 151, 35));
        label_Mercury_run->setFont(font7);
        light_waypoint = new QLabel(frame_Node_status);
        light_waypoint->setObjectName(QString::fromUtf8("light_waypoint"));
        light_waypoint->setGeometry(QRect(180, 267, 41, 20));
        light_waypoint->setFont(font7);
        light_waypoint->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);"));
        light_waypoint->setAlignment(Qt::AlignCenter);
        light_Mercury_run = new QLabel(frame_Node_status);
        light_Mercury_run->setObjectName(QString::fromUtf8("light_Mercury_run"));
        light_Mercury_run->setGeometry(QRect(180, 237, 41, 20));
        light_Mercury_run->setFont(font7);
        light_Mercury_run->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);"));
        light_Mercury_run->setAlignment(Qt::AlignCenter);
        label_path_following = new QLabel(frame_Node_status);
        label_path_following->setObjectName(QString::fromUtf8("label_path_following"));
        label_path_following->setGeometry(QRect(240, 80, 151, 35));
        label_path_following->setFont(font7);
        label_path_plannning = new QLabel(frame_Node_status);
        label_path_plannning->setObjectName(QString::fromUtf8("label_path_plannning"));
        label_path_plannning->setGeometry(QRect(240, 50, 151, 35));
        label_path_plannning->setFont(font7);
        label_road_sign = new QLabel(frame_Node_status);
        label_road_sign->setObjectName(QString::fromUtf8("label_road_sign"));
        label_road_sign->setGeometry(QRect(240, 290, 151, 35));
        label_road_sign->setFont(font7);
        label_obstacle = new QLabel(frame_Node_status);
        label_obstacle->setObjectName(QString::fromUtf8("label_obstacle"));
        label_obstacle->setGeometry(QRect(240, 140, 151, 35));
        label_obstacle->setFont(font7);
        label_logger = new QLabel(frame_Node_status);
        label_logger->setObjectName(QString::fromUtf8("label_logger"));
        label_logger->setGeometry(QRect(20, 290, 151, 35));
        label_logger->setFont(font7);
        light_path_planning = new QLabel(frame_Node_status);
        light_path_planning->setObjectName(QString::fromUtf8("light_path_planning"));
        light_path_planning->setGeometry(QRect(400, 57, 41, 20));
        light_path_planning->setFont(font7);
        light_path_planning->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);"));
        light_path_planning->setAlignment(Qt::AlignCenter);
        light_path_following = new QLabel(frame_Node_status);
        light_path_following->setObjectName(QString::fromUtf8("light_path_following"));
        light_path_following->setGeometry(QRect(400, 87, 41, 20));
        light_path_following->setFont(font7);
        light_path_following->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);"));
        light_path_following->setAlignment(Qt::AlignCenter);
        light_points_proc = new QLabel(frame_Node_status);
        light_points_proc->setObjectName(QString::fromUtf8("light_points_proc"));
        light_points_proc->setGeometry(QRect(400, 177, 41, 20));
        light_points_proc->setFont(font7);
        light_points_proc->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);"));
        light_points_proc->setAlignment(Qt::AlignCenter);
        light_road_sign = new QLabel(frame_Node_status);
        light_road_sign->setObjectName(QString::fromUtf8("light_road_sign"));
        light_road_sign->setGeometry(QRect(400, 300, 41, 20));
        light_road_sign->setFont(font7);
        light_road_sign->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);"));
        light_road_sign->setAlignment(Qt::AlignCenter);
        light_logger = new QLabel(frame_Node_status);
        light_logger->setObjectName(QString::fromUtf8("light_logger"));
        light_logger->setGeometry(QRect(180, 297, 41, 20));
        light_logger->setFont(font7);
        light_logger->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);"));
        light_logger->setAlignment(Qt::AlignCenter);
        label_locator = new QLabel(frame_Node_status);
        label_locator->setObjectName(QString::fromUtf8("label_locator"));
        label_locator->setGeometry(QRect(240, 110, 151, 35));
        label_locator->setFont(font7);
        label_points_proc = new QLabel(frame_Node_status);
        label_points_proc->setObjectName(QString::fromUtf8("label_points_proc"));
        label_points_proc->setGeometry(QRect(240, 170, 151, 35));
        label_points_proc->setFont(font7);
        light_obstacle = new QLabel(frame_Node_status);
        light_obstacle->setObjectName(QString::fromUtf8("light_obstacle"));
        light_obstacle->setGeometry(QRect(400, 147, 41, 20));
        light_obstacle->setFont(font7);
        light_obstacle->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);"));
        light_obstacle->setAlignment(Qt::AlignCenter);
        light_locator = new QLabel(frame_Node_status);
        light_locator->setObjectName(QString::fromUtf8("light_locator"));
        light_locator->setGeometry(QRect(400, 117, 41, 20));
        light_locator->setFont(font7);
        light_locator->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);"));
        light_locator->setAlignment(Qt::AlignCenter);
        light_joystick = new QLabel(frame_Node_status);
        light_joystick->setObjectName(QString::fromUtf8("light_joystick"));
        light_joystick->setGeometry(QRect(400, 208, 41, 20));
        light_joystick->setFont(font7);
        light_joystick->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);"));
        light_joystick->setAlignment(Qt::AlignCenter);
        label_joystick = new QLabel(frame_Node_status);
        label_joystick->setObjectName(QString::fromUtf8("label_joystick"));
        label_joystick->setGeometry(QRect(240, 200, 151, 35));
        label_joystick->setFont(font7);
        light_container = new QLabel(frame_Node_status);
        light_container->setObjectName(QString::fromUtf8("light_container"));
        light_container->setGeometry(QRect(400, 240, 41, 20));
        light_container->setFont(font7);
        light_container->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);"));
        light_container->setAlignment(Qt::AlignCenter);
        label_container = new QLabel(frame_Node_status);
        label_container->setObjectName(QString::fromUtf8("label_container"));
        label_container->setGeometry(QRect(240, 230, 151, 35));
        label_container->setFont(font7);
        label_traffic_light = new QLabel(frame_Node_status);
        label_traffic_light->setObjectName(QString::fromUtf8("label_traffic_light"));
        label_traffic_light->setGeometry(QRect(240, 260, 151, 35));
        label_traffic_light->setFont(font7);
        light_traffic_light = new QLabel(frame_Node_status);
        light_traffic_light->setObjectName(QString::fromUtf8("light_traffic_light"));
        light_traffic_light->setGeometry(QRect(400, 270, 41, 20));
        light_traffic_light->setFont(font7);
        light_traffic_light->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);"));
        light_traffic_light->setAlignment(Qt::AlignCenter);
        frame_map = new QFrame(centralwidget);
        frame_map->setObjectName(QString::fromUtf8("frame_map"));
        frame_map->setGeometry(QRect(10, 10, 1271, 491));
        frame_map->setFrameShape(QFrame::StyledPanel);
        frame_map->setFrameShadow(QFrame::Raised);
        img_obstacle_detector = new QLabel(frame_map);
        img_obstacle_detector->setObjectName(QString::fromUtf8("img_obstacle_detector"));
        img_obstacle_detector->setGeometry(QRect(780, 40, 300, 300));
        img_obstacle_detector->setStyleSheet(QString::fromUtf8("background-color: rgb(114, 159, 207);"));
        label_obstacle_detector = new QLabel(frame_map);
        label_obstacle_detector->setObjectName(QString::fromUtf8("label_obstacle_detector"));
        label_obstacle_detector->setGeometry(QRect(780, 10, 301, 31));
        label_obstacle_detector->setFont(font);
        img_matcing_img = new QLabel(frame_map);
        img_matcing_img->setObjectName(QString::fromUtf8("img_matcing_img"));
        img_matcing_img->setGeometry(QRect(470, 40, 300, 300));
        img_matcing_img->setStyleSheet(QString::fromUtf8("background-color: rgb(114, 159, 207);"));
        label_matching_img = new QLabel(frame_map);
        label_matching_img->setObjectName(QString::fromUtf8("label_matching_img"));
        label_matching_img->setGeometry(QRect(470, 10, 301, 31));
        label_matching_img->setFont(font);
        img_map = new QLabel(frame_map);
        img_map->setObjectName(QString::fromUtf8("img_map"));
        img_map->setGeometry(QRect(20, 40, 440, 440));
        img_map->setStyleSheet(QString::fromUtf8("background-color:rgb(114, 159, 207);"));
        label_map = new QLabel(frame_map);
        label_map->setObjectName(QString::fromUtf8("label_map"));
        label_map->setGeometry(QRect(20, 10, 441, 31));
        label_map->setFont(font1);
        frame_waypoint = new QFrame(frame_map);
        frame_waypoint->setObjectName(QString::fromUtf8("frame_waypoint"));
        frame_waypoint->setGeometry(QRect(470, 350, 791, 131));
        frame_waypoint->setFrameShape(QFrame::StyledPanel);
        frame_waypoint->setFrameShadow(QFrame::Raised);
        label_waypoint_2 = new QLabel(frame_waypoint);
        label_waypoint_2->setObjectName(QString::fromUtf8("label_waypoint_2"));
        label_waypoint_2->setGeometry(QRect(10, 10, 121, 31));
        label_waypoint_2->setFont(font);
        label_waypoint_file = new QLabel(frame_waypoint);
        label_waypoint_file->setObjectName(QString::fromUtf8("label_waypoint_file"));
        label_waypoint_file->setGeometry(QRect(10, 50, 91, 31));
        QFont font8;
        font8.setPointSize(14);
        label_waypoint_file->setFont(font8);
        label_waypoint_index = new QLabel(frame_waypoint);
        label_waypoint_index->setObjectName(QString::fromUtf8("label_waypoint_index"));
        label_waypoint_index->setGeometry(QRect(610, 50, 81, 31));
        label_waypoint_index->setFont(font8);
        box_waypoint_file = new QLabel(frame_waypoint);
        box_waypoint_file->setObjectName(QString::fromUtf8("box_waypoint_file"));
        box_waypoint_file->setGeometry(QRect(100, 50, 501, 31));
        box_waypoint_file->setFont(font2);
        box_waypoint_file->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        box_waypoint_file->setAlignment(Qt::AlignCenter);
        box_waypoint_index = new QLabel(frame_waypoint);
        box_waypoint_index->setObjectName(QString::fromUtf8("box_waypoint_index"));
        box_waypoint_index->setGeometry(QRect(610, 90, 171, 31));
        box_waypoint_index->setFont(font2);
        box_waypoint_index->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        box_waypoint_index->setAlignment(Qt::AlignCenter);
        box_waypoint_map = new QLabel(frame_waypoint);
        box_waypoint_map->setObjectName(QString::fromUtf8("box_waypoint_map"));
        box_waypoint_map->setGeometry(QRect(100, 90, 501, 31));
        box_waypoint_map->setFont(font2);
        box_waypoint_map->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        box_waypoint_map->setAlignment(Qt::AlignCenter);
        label_waypoint_map = new QLabel(frame_waypoint);
        label_waypoint_map->setObjectName(QString::fromUtf8("label_waypoint_map"));
        label_waypoint_map->setGeometry(QRect(10, 90, 91, 31));
        label_waypoint_map->setFont(font8);
        frame_camera = new QFrame(centralwidget);
        frame_camera->setObjectName(QString::fromUtf8("frame_camera"));
        frame_camera->setGeometry(QRect(400, 510, 501, 381));
        frame_camera->setFrameShape(QFrame::StyledPanel);
        frame_camera->setFrameShadow(QFrame::Raised);
        label_camera = new QLabel(frame_camera);
        label_camera->setObjectName(QString::fromUtf8("label_camera"));
        label_camera->setGeometry(QRect(10, 10, 481, 31));
        label_camera->setFont(font);
        img_camera = new QLabel(frame_camera);
        img_camera->setObjectName(QString::fromUtf8("img_camera"));
        img_camera->setGeometry(QRect(10, 70, 480, 270));
        img_camera->setMinimumSize(QSize(480, 270));
        img_camera->setMaximumSize(QSize(480, 270));
        img_camera->setStyleSheet(QString::fromUtf8("background-color: rgb(173, 127, 168);"));
        frame_robot_control = new QFrame(centralwidget);
        frame_robot_control->setObjectName(QString::fromUtf8("frame_robot_control"));
        frame_robot_control->setGeometry(QRect(910, 510, 371, 131));
        frame_robot_control->setFrameShape(QFrame::StyledPanel);
        frame_robot_control->setFrameShadow(QFrame::Raised);
        label_robot_control = new QLabel(frame_robot_control);
        label_robot_control->setObjectName(QString::fromUtf8("label_robot_control"));
        label_robot_control->setGeometry(QRect(6, 10, 361, 21));
        label_robot_control->setFont(font);
        label_velocity = new QLabel(frame_robot_control);
        label_velocity->setObjectName(QString::fromUtf8("label_velocity"));
        label_velocity->setGeometry(QRect(10, 70, 81, 21));
        label_velocity->setFont(font8);
        label_potential = new QLabel(frame_robot_control);
        label_potential->setObjectName(QString::fromUtf8("label_potential"));
        label_potential->setGeometry(QRect(10, 100, 81, 21));
        label_potential->setFont(font8);
        label_x1 = new QLabel(frame_robot_control);
        label_x1->setObjectName(QString::fromUtf8("label_x1"));
        label_x1->setGeometry(QRect(213, 40, 51, 20));
        label_x1->setAlignment(Qt::AlignCenter);
        label_velocity_x = new QLabel(frame_robot_control);
        label_velocity_x->setObjectName(QString::fromUtf8("label_velocity_x"));
        label_velocity_x->setGeometry(QRect(210, 70, 61, 21));
        label_velocity_x->setStyleSheet(QString::fromUtf8("background-color: rgb(211, 215, 207);\n"
"border-color:rgb(0, 0, 0); border-style:solid; border-width:2px;"));
        label_velocity_x->setAlignment(Qt::AlignCenter);
        label_velocity_yaw = new QLabel(frame_robot_control);
        label_velocity_yaw->setObjectName(QString::fromUtf8("label_velocity_yaw"));
        label_velocity_yaw->setGeometry(QRect(304, 70, 61, 21));
        label_velocity_yaw->setStyleSheet(QString::fromUtf8("background-color: rgb(211, 215, 207);\n"
"border-color:rgb(0, 0, 0); border-style:solid; border-width:2px;"));
        label_velocity_yaw->setAlignment(Qt::AlignCenter);
        label_potential_x = new QLabel(frame_robot_control);
        label_potential_x->setObjectName(QString::fromUtf8("label_potential_x"));
        label_potential_x->setGeometry(QRect(210, 100, 61, 21));
        label_potential_x->setStyleSheet(QString::fromUtf8("background-color: rgb(211, 215, 207);\n"
"border-color:rgb(0, 0, 0); border-style:solid; border-width:2px;"));
        label_potential_x->setAlignment(Qt::AlignCenter);
        label_potential_yaw = new QLabel(frame_robot_control);
        label_potential_yaw->setObjectName(QString::fromUtf8("label_potential_yaw"));
        label_potential_yaw->setGeometry(QRect(304, 100, 61, 21));
        label_potential_yaw->setStyleSheet(QString::fromUtf8("background-color: rgb(211, 215, 207);\n"
"border-color:rgb(0, 0, 0); border-style:solid; border-width:2px;"));
        label_potential_yaw->setAlignment(Qt::AlignCenter);
        label_y1 = new QLabel(frame_robot_control);
        label_y1->setObjectName(QString::fromUtf8("label_y1"));
        label_y1->setGeometry(QRect(310, 40, 51, 20));
        label_y1->setAlignment(Qt::AlignCenter);
        frame_imu = new QFrame(centralwidget);
        frame_imu->setObjectName(QString::fromUtf8("frame_imu"));
        frame_imu->setGeometry(QRect(910, 650, 371, 161));
        frame_imu->setFrameShape(QFrame::StyledPanel);
        frame_imu->setFrameShadow(QFrame::Raised);
        label_imu = new QLabel(frame_imu);
        label_imu->setObjectName(QString::fromUtf8("label_imu"));
        label_imu->setGeometry(QRect(10, 10, 351, 21));
        label_imu->setFont(font);
        label_x2 = new QLabel(frame_imu);
        label_x2->setObjectName(QString::fromUtf8("label_x2"));
        label_x2->setGeometry(QRect(125, 40, 51, 21));
        label_x2->setAlignment(Qt::AlignCenter);
        label_y2 = new QLabel(frame_imu);
        label_y2->setObjectName(QString::fromUtf8("label_y2"));
        label_y2->setGeometry(QRect(215, 40, 51, 20));
        label_y2->setAlignment(Qt::AlignCenter);
        label_gyro_x = new QLabel(frame_imu);
        label_gyro_x->setObjectName(QString::fromUtf8("label_gyro_x"));
        label_gyro_x->setGeometry(QRect(120, 100, 61, 21));
        label_gyro_x->setStyleSheet(QString::fromUtf8("background-color: rgb(211, 215, 207);\n"
"border-color:rgb(0, 0, 0); border-style:solid; border-width:2px;"));
        label_gyro_x->setAlignment(Qt::AlignCenter);
        label_gyro_y = new QLabel(frame_imu);
        label_gyro_y->setObjectName(QString::fromUtf8("label_gyro_y"));
        label_gyro_y->setGeometry(QRect(210, 100, 61, 21));
        label_gyro_y->setStyleSheet(QString::fromUtf8("background-color: rgb(211, 215, 207);\n"
"border-color:rgb(0, 0, 0); border-style:solid; border-width:2px;"));
        label_gyro_y->setAlignment(Qt::AlignCenter);
        label_accele_x = new QLabel(frame_imu);
        label_accele_x->setObjectName(QString::fromUtf8("label_accele_x"));
        label_accele_x->setGeometry(QRect(120, 70, 61, 21));
        label_accele_x->setStyleSheet(QString::fromUtf8("background-color: rgb(211, 215, 207);\n"
"border-color:rgb(0, 0, 0); border-style:solid; border-width:2px;"));
        label_accele_x->setAlignment(Qt::AlignCenter);
        label_accele_y = new QLabel(frame_imu);
        label_accele_y->setObjectName(QString::fromUtf8("label_accele_y"));
        label_accele_y->setGeometry(QRect(210, 70, 61, 21));
        label_accele_y->setStyleSheet(QString::fromUtf8("background-color: rgb(211, 215, 207);\n"
"border-color:rgb(0, 0, 0); border-style:solid; border-width:2px;"));
        label_accele_y->setAlignment(Qt::AlignCenter);
        label_angle_x = new QLabel(frame_imu);
        label_angle_x->setObjectName(QString::fromUtf8("label_angle_x"));
        label_angle_x->setGeometry(QRect(120, 130, 61, 21));
        label_angle_x->setStyleSheet(QString::fromUtf8("background-color: rgb(211, 215, 207);\n"
"border-color:rgb(0, 0, 0); border-style:solid; border-width:2px;"));
        label_angle_x->setAlignment(Qt::AlignCenter);
        label_angle_y = new QLabel(frame_imu);
        label_angle_y->setObjectName(QString::fromUtf8("label_angle_y"));
        label_angle_y->setGeometry(QRect(210, 130, 61, 21));
        label_angle_y->setStyleSheet(QString::fromUtf8("background-color: rgb(211, 215, 207);\n"
"border-color:rgb(0, 0, 0); border-style:solid; border-width:2px;"));
        label_angle_y->setAlignment(Qt::AlignCenter);
        label_angle_z = new QLabel(frame_imu);
        label_angle_z->setObjectName(QString::fromUtf8("label_angle_z"));
        label_angle_z->setGeometry(QRect(300, 130, 61, 21));
        label_angle_z->setStyleSheet(QString::fromUtf8("background-color: rgb(211, 215, 207);\n"
"border-color:rgb(0, 0, 0); border-style:solid; border-width:2px;"));
        label_angle_z->setAlignment(Qt::AlignCenter);
        label_accele_z = new QLabel(frame_imu);
        label_accele_z->setObjectName(QString::fromUtf8("label_accele_z"));
        label_accele_z->setGeometry(QRect(300, 70, 61, 21));
        label_accele_z->setStyleSheet(QString::fromUtf8("background-color: rgb(211, 215, 207);\n"
"border-color:rgb(0, 0, 0); border-style:solid; border-width:2px;"));
        label_accele_z->setAlignment(Qt::AlignCenter);
        label_z2 = new QLabel(frame_imu);
        label_z2->setObjectName(QString::fromUtf8("label_z2"));
        label_z2->setGeometry(QRect(306, 40, 51, 20));
        label_z2->setAlignment(Qt::AlignCenter);
        label_gyro_z = new QLabel(frame_imu);
        label_gyro_z->setObjectName(QString::fromUtf8("label_gyro_z"));
        label_gyro_z->setGeometry(QRect(300, 100, 61, 21));
        label_gyro_z->setStyleSheet(QString::fromUtf8("background-color: rgb(211, 215, 207);\n"
"border-color:rgb(0, 0, 0); border-style:solid; border-width:2px;"));
        label_gyro_z->setAlignment(Qt::AlignCenter);
        label_accele = new QLabel(frame_imu);
        label_accele->setObjectName(QString::fromUtf8("label_accele"));
        label_accele->setGeometry(QRect(10, 70, 91, 21));
        label_accele->setFont(font8);
        label_angle = new QLabel(frame_imu);
        label_angle->setObjectName(QString::fromUtf8("label_angle"));
        label_angle->setGeometry(QRect(10, 130, 91, 21));
        label_angle->setFont(font8);
        label_gyro = new QLabel(frame_imu);
        label_gyro->setObjectName(QString::fromUtf8("label_gyro"));
        label_gyro->setGeometry(QRect(10, 100, 91, 21));
        label_gyro->setFont(font8);
        frame = new QFrame(centralwidget);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(910, 820, 831, 71));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        box_filename = new QLabel(frame);
        box_filename->setObjectName(QString::fromUtf8("box_filename"));
        box_filename->setGeometry(QRect(130, 30, 311, 31));
        box_filename->setFont(font2);
        box_filename->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        box_filename->setAlignment(Qt::AlignCenter);
        label_auto = new QLabel(frame);
        label_auto->setObjectName(QString::fromUtf8("label_auto"));
        label_auto->setGeometry(QRect(640, 30, 61, 31));
        label_auto->setFont(font2);
        box_auto = new QLabel(frame);
        box_auto->setObjectName(QString::fromUtf8("box_auto"));
        box_auto->setGeometry(QRect(700, 30, 121, 31));
        box_auto->setFont(font2);
        box_auto->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        box_auto->setAlignment(Qt::AlignCenter);
        box_manual = new QLabel(frame);
        box_manual->setObjectName(QString::fromUtf8("box_manual"));
        box_manual->setGeometry(QRect(530, 30, 101, 31));
        box_manual->setFont(font2);
        box_manual->setStyleSheet(QString::fromUtf8("background-color: rgb(243, 243, 243);"));
        box_manual->setAlignment(Qt::AlignCenter);
        label_manual = new QLabel(frame);
        label_manual->setObjectName(QString::fromUtf8("label_manual"));
        label_manual->setGeometry(QRect(450, 30, 81, 31));
        label_manual->setFont(font2);
        label_filename = new QLabel(frame);
        label_filename->setObjectName(QString::fromUtf8("label_filename"));
        label_filename->setGeometry(QRect(10, 30, 111, 31));
        label_filename->setFont(font2);
        label_node_status_2 = new QLabel(frame);
        label_node_status_2->setObjectName(QString::fromUtf8("label_node_status_2"));
        label_node_status_2->setGeometry(QRect(10, 2, 51, 31));
        label_node_status_2->setFont(font);
        Monitor2023->setCentralWidget(centralwidget);
        menubar = new QMenuBar(Monitor2023);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 1750, 28));
        Monitor2023->setMenuBar(menubar);
        statusbar = new QStatusBar(Monitor2023);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        Monitor2023->setStatusBar(statusbar);

        retranslateUi(Monitor2023);

        QMetaObject::connectSlotsByName(Monitor2023);
    } // setupUi

    void retranslateUi(QMainWindow *Monitor2023)
    {
        Monitor2023->setWindowTitle(QApplication::translate("Monitor2023", "Monitor2023", nullptr));
        img_depth->setText(QString());
        label_depth->setText(QApplication::translate("Monitor2023", "Depth Img", nullptr));
        label_reflectivity->setText(QApplication::translate("Monitor2023", "Reflectivity Img", nullptr));
        img_reflectivity->setText(QString());
        label_mercury_status->setText(QApplication::translate("Monitor2023", "Mercury Status", nullptr));
        label_temp->setText(QApplication::translate("Monitor2023", "Temp", nullptr));
        label_temp_CPU->setText(QApplication::translate("Monitor2023", "CPU Temp", nullptr));
        label_battery->setText(QApplication::translate("Monitor2023", "Battery", nullptr));
        progressBar_temp->setFormat(QApplication::translate("Monitor2023", "%p\342\204\203", nullptr));
        progressBar_temp_CPU->setFormat(QApplication::translate("Monitor2023", "%p\342\204\203", nullptr));
        Mercury->setText(QApplication::translate("Monitor2023", "Mercury", nullptr));
        label_sonar->setText(QApplication::translate("Monitor2023", "Sonar", nullptr));
        Sonar_front_left->setText(QApplication::translate("Monitor2023", "-", nullptr));
        Sonar_front_center->setText(QApplication::translate("Monitor2023", "-", nullptr));
        Sonar_front_right->setText(QApplication::translate("Monitor2023", "-", nullptr));
        Sonar_left->setText(QApplication::translate("Monitor2023", "-", nullptr));
        Sonar_right->setText(QApplication::translate("Monitor2023", "-", nullptr));
        Sonar_rear_left->setText(QApplication::translate("Monitor2023", "-", nullptr));
        Sonar_rear_right->setText(QApplication::translate("Monitor2023", "-", nullptr));
        label_bolt->setText(QApplication::translate("Monitor2023", "28.6 V", nullptr));
        tire_front_left->setText(QString());
        tire_front_right->setText(QString());
        tire_rear_left->setText(QString());
        tire_rear_right->setText(QString());
        label_mileage->setText(QApplication::translate("Monitor2023", "Mileage :", nullptr));
        box_mileage->setText(QApplication::translate("Monitor2023", "0", nullptr));
        label_mileage_m->setText(QApplication::translate("Monitor2023", "m", nullptr));
        rpm_front_right->setText(QApplication::translate("Monitor2023", "-", nullptr));
        rpm_rear_right->setText(QApplication::translate("Monitor2023", "-", nullptr));
        rpm_rear_left->setText(QApplication::translate("Monitor2023", "-", nullptr));
        rpm_front_left->setText(QApplication::translate("Monitor2023", "-", nullptr));
        label_node_status->setText(QApplication::translate("Monitor2023", "Node Status", nullptr));
        label_3DLiDAR_H->setText(QApplication::translate("Monitor2023", "3D LiDAR(H)", nullptr));
        light_3DLiDAR_H->setText(QString());
        label_3DLiDAR_M->setText(QApplication::translate("Monitor2023", "3D LiDAR(M)", nullptr));
        light_3DLiDAR_M->setText(QString());
        label_2DLiDAR_L->setText(QApplication::translate("Monitor2023", "2D LiDAR(L)", nullptr));
        light_2DLiDAR_L->setText(QString());
        label_camera_status->setText(QApplication::translate("Monitor2023", "Camera(F)", nullptr));
        light_camera_status->setText(QString());
        label_Mercury->setText(QApplication::translate("Monitor2023", "Mercury", nullptr));
        label_Sonar->setText(QApplication::translate("Monitor2023", "Sonar", nullptr));
        label_waypoint->setText(QApplication::translate("Monitor2023", "Waypoint", nullptr));
        light_Mercury->setText(QString());
        light_sonar->setText(QString());
        label_Mercury_run->setText(QApplication::translate("Monitor2023", "MercuryRun", nullptr));
        light_waypoint->setText(QString());
        light_Mercury_run->setText(QString());
        label_path_following->setText(QApplication::translate("Monitor2023", "PathFollowing", nullptr));
        label_path_plannning->setText(QApplication::translate("Monitor2023", "PathPlanning", nullptr));
        label_road_sign->setText(QApplication::translate("Monitor2023", "RoadSign", nullptr));
        label_obstacle->setText(QApplication::translate("Monitor2023", "Obstacle", nullptr));
        label_logger->setText(QApplication::translate("Monitor2023", "Logger", nullptr));
        light_path_planning->setText(QString());
        light_path_following->setText(QString());
        light_points_proc->setText(QString());
        light_road_sign->setText(QString());
        light_logger->setText(QString());
        label_locator->setText(QApplication::translate("Monitor2023", "Locator", nullptr));
        label_points_proc->setText(QApplication::translate("Monitor2023", "PointsProc", nullptr));
        light_obstacle->setText(QString());
        light_locator->setText(QString());
        light_joystick->setText(QString());
        label_joystick->setText(QApplication::translate("Monitor2023", "Joystick", nullptr));
        light_container->setText(QString());
        label_container->setText(QApplication::translate("Monitor2023", "Container", nullptr));
        label_traffic_light->setText(QApplication::translate("Monitor2023", "TrafficLight", nullptr));
        light_traffic_light->setText(QString());
        img_obstacle_detector->setText(QString());
        label_obstacle_detector->setText(QApplication::translate("Monitor2023", "Obstacle Detector", nullptr));
        img_matcing_img->setText(QString());
        label_matching_img->setText(QApplication::translate("Monitor2023", "Matching Img", nullptr));
#ifndef QT_NO_TOOLTIP
        img_map->setToolTip(QApplication::translate("Monitor2023", "<html><head/><body><p><br/></p></body></html>", nullptr));
#endif // QT_NO_TOOLTIP
        img_map->setText(QString());
        label_map->setText(QApplication::translate("Monitor2023", "Map", nullptr));
        label_waypoint_2->setText(QApplication::translate("Monitor2023", "Way Point", nullptr));
        label_waypoint_file->setText(QApplication::translate("Monitor2023", "filename", nullptr));
        label_waypoint_index->setText(QApplication::translate("Monitor2023", "index", nullptr));
        box_waypoint_file->setText(QApplication::translate("Monitor2023", "-", nullptr));
        box_waypoint_index->setText(QApplication::translate("Monitor2023", "-", nullptr));
        box_waypoint_map->setText(QApplication::translate("Monitor2023", "-", nullptr));
        label_waypoint_map->setText(QApplication::translate("Monitor2023", "mapname", nullptr));
        label_camera->setText(QApplication::translate("Monitor2023", "Front Camera", nullptr));
        img_camera->setText(QString());
        label_robot_control->setText(QApplication::translate("Monitor2023", "Robot Control", nullptr));
        label_velocity->setText(QApplication::translate("Monitor2023", "velocity", nullptr));
        label_potential->setText(QApplication::translate("Monitor2023", "potential", nullptr));
        label_x1->setText(QApplication::translate("Monitor2023", "X-axis", nullptr));
        label_velocity_x->setText(QApplication::translate("Monitor2023", "-", nullptr));
        label_velocity_yaw->setText(QApplication::translate("Monitor2023", "-", nullptr));
        label_potential_x->setText(QApplication::translate("Monitor2023", "-", nullptr));
        label_potential_yaw->setText(QApplication::translate("Monitor2023", "-", nullptr));
        label_y1->setText(QApplication::translate("Monitor2023", "Yaw", nullptr));
        label_imu->setText(QApplication::translate("Monitor2023", "IMU", nullptr));
        label_x2->setText(QApplication::translate("Monitor2023", "X-axis", nullptr));
        label_y2->setText(QApplication::translate("Monitor2023", "Y-axis", nullptr));
        label_gyro_x->setText(QApplication::translate("Monitor2023", "-", nullptr));
        label_gyro_y->setText(QApplication::translate("Monitor2023", "-", nullptr));
        label_accele_x->setText(QApplication::translate("Monitor2023", "-", nullptr));
        label_accele_y->setText(QApplication::translate("Monitor2023", "-", nullptr));
        label_angle_x->setText(QApplication::translate("Monitor2023", "-", nullptr));
        label_angle_y->setText(QApplication::translate("Monitor2023", "-", nullptr));
        label_angle_z->setText(QApplication::translate("Monitor2023", "-", nullptr));
        label_accele_z->setText(QApplication::translate("Monitor2023", "-", nullptr));
        label_z2->setText(QApplication::translate("Monitor2023", "Z-axis", nullptr));
        label_gyro_z->setText(QApplication::translate("Monitor2023", "-", nullptr));
        label_accele->setText(QApplication::translate("Monitor2023", "accele", nullptr));
        label_angle->setText(QApplication::translate("Monitor2023", "angle", nullptr));
        label_gyro->setText(QApplication::translate("Monitor2023", "gyro", nullptr));
        box_filename->setText(QApplication::translate("Monitor2023", "-", nullptr));
        label_auto->setText(QApplication::translate("Monitor2023", "Auto", nullptr));
        box_auto->setText(QApplication::translate("Monitor2023", "-", nullptr));
        box_manual->setText(QApplication::translate("Monitor2023", "-", nullptr));
        label_manual->setText(QApplication::translate("Monitor2023", "Manual:", nullptr));
        label_filename->setText(QApplication::translate("Monitor2023", "Foldername :", nullptr));
        label_node_status_2->setText(QApplication::translate("Monitor2023", "Log", nullptr));
    } // retranslateUi

};

namespace Ui {
    class Monitor2023: public Ui_Monitor2023 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MONITOR2023_H
